# Generated by Django 5.1.4 on 2024-12-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadAireLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('horario', models.TextField()),
                ('equipo_necesario', models.TextField()),
                ('nivel_dificultad', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], max_length=20)),
                ('opiniones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtraccionTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('horario', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opiniones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('horario', models.TextField()),
                ('productos', models.TextField()),
                ('opiniones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CulturaOcio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('museo', 'Museo'), ('teatro', 'Teatro'), ('galeria', 'Galería'), ('centro_cultural', 'Centro Cultural'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('horario', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opiniones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_cocina', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('horario', models.TextField()),
                ('opiniones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VidaNocturna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('bar', 'Bar'), ('club', 'Club'), ('discoteca', 'Discoteca'), ('pub', 'Pub'), ('otro', 'Otro')], max_length=20)),
                ('direccion', models.TextField()),
                ('horario', models.TextField()),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opiniones', models.TextField(blank=True)),
            ],
        ),
    ]
